version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    target-branch: "develop"
    reviewers:
      - "@terragonlabs/core-team"
    assignees:
      - "@terragonlabs/security-team"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    milestone: "dependency-updates"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
    target-branch: "develop"
    reviewers:
      - "@terragonlabs/devops-team"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    target-branch: "develop"
    reviewers:
      - "@terragonlabs/devops-team"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    labels:
      - "docker"
      - "automated"