# Hadolint configuration for advanced Docker optimization
ignored:
  - DL3008  # Pin versions in apt get install
  - DL3009  # Delete the apt-get lists after installing something
  - DL3015  # Avoid additional packages by specifying --no-install-recommends

trusted-registries:
  - docker.io
  - gcr.io
  - registry.hub.docker.com

override:
  error:
    - DL3001  # Switching to root user
    - DL3002  # Last user should not be root
    - DL3025  # Use arguments JSON notation for CMD and ENTRYPOINT
  warning:
    - DL3018  # Pin versions in apk add
    - DL3019  # Use the --no-cache switch
  info:
    - DL3032  # `yum clean all` missing
  style:
    - DL3033  # Specify version with `yum install -y <package>-<version>`