[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "iot_anomaly_detector_timeseries"
version = "0.0.3"
requires-python = ">=3.8"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["iot_anomaly_detector_timeseries"]
