apiVersion: v1
data:
  BATCH_SIZE: '32'
  ENVIRONMENT: production
  LOG_LEVEL: INFO
  MAX_WORKERS: '8'
  MODEL_PATH: /app/saved_models
kind: ConfigMap
metadata:
  name: iot-anomaly-detector-config
  namespace: iot-anomaly-detector
